" https://github.com/tpope/vim-pathogen
execute pathogen#infect()
syntax on

filetype plugin indent on
set tabstop=2
set shiftwidth=2
set expandtab

set background=dark
colorscheme solarized

set ruler

"set number

"Syntastic - Syntax checker
"https://github.com/scrooloose/syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

"vim-airline
"https://github.com/bling/vim-airline
set laststatus=2
set term=xterm-256color
set termencoding=utf-8
let g:Powerline_symbols = 'fancy'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
